### ISSUE TITLE
Use OutputDevice instead of extension for printing

### ISSUE THREAD

**Issue by nallath** [Spenbert02/FisnarRobotPlugin#5]
The plugin currently uses an extension to handle the printing, which isn't the recommended way of doing it. I would suggest having a look at OutputDevices. The closest thing that Cura currently has is probably the USBPrintingOutputDevice: https://github.com/Ultimaker/Cura/blob/main/plugins/USBPrinting/USBPrinterOutputDevice.py

It has a number of advantages over the approach that you chose. Primarily that you can use the monitor page to display information about the print in progress. It also allows you to add automatic detection of the serial connection. Last but not least, you could also add manual control to the robot by means of jogging controls.

**Comment by Spenbert02** [comment]
Ah this is something I thought about looking into. Unfortunately the device I'm writing to uses the RS232 protocol (over USB still), so I'll look into whether the USBPrinterOutputDevice class will still work.

**Comment by nallath** [comment]
I meant it more like something to get inspiration from. We also use the output devices to connect with various network devices. It's intended to support all kinds of protocols.

**Comment by Spenbert02** [comment]
Alright, it took me a while but I've reimplemented all serial communication under the FisnarOutputDevice class. This uses a lot of the same logic as USBPrinterOutputDevice, but has some added complications because there are actually several peripherals to communicate with. I've resubmitted the plugin via the Ultimaker Contributor Portal - let me know if you find any more issues or areas for improvement.
